<?php
/**
 * Magmodules.eu - http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category      Magmodules
 * @package       Magmodules_Ekomisnippets
 * @author        Magmodules <info@magmodules.eu>
 * @copyright     Copyright (c) 2017 (http://www.magmodules.eu)
 * @license       http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($_snippets = $this->getSnapshopRequest()) { ?>
    <div class="ekomi-shop-snippets">
        <?php echo $this->getEkomiStars($_snippets['fb_avg']); ?>
        <div class="ekomi-schema" itemscope="itemscope" itemtype="http://schema.org/WebPage">
            <div itemprop="aggregateRating" itemscope="itemscope" itemtype="http://schema.org/AggregateRating">
                <meta itemprop="bestRating" content="5">
                <p><?php echo Mage::helper('ekomisnippets')->__('Rating') ?>
                    <span itemprop="ratingValue"><?php echo $_snippets['fb_avg']; ?></span>
                    <?php echo Mage::helper('ekomisnippets')->__('based on') ?>
                    <span itemprop="reviewCount"><?php echo $_snippets['fb_count']; ?></span>
                    <?php echo $this->getEkomiLink(); ?>
                </p>
            </div>
        </div>
    </div>
<?php } ?>